## YAML Template.
## Cargar las Rutas definidas
app_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix: /
   
## Routing for Users
app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user
    
## Routing for Projects
app_project:
    resource: "@AppBundle/Resources/config/routing/project.yml"
    prefix: /project
    
## Routing for Agencys
app_agency:
    resource: "@AppBundle/Resources/config/routing/agency.yml"
    prefix: /agency   
 