BackendBundle\Entity\TblAdmonFinanciero:
    type: entity
    table: tbl_admon_financiero
    indexes:
        IDX_614C90042FE17928:
            columns:
                - id_organizacion
    id:
        idRegistro:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_registro
            generator:
                strategy: SEQUENCE
    fields:
        idProyecto:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_proyecto
        nombreAdmonFinanciero:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: nombre_admon_financiero
    manyToOne:
        idOrganizacion:
            targetEntity: TblOrganizaciones
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_organizacion:
                    referencedColumnName: id_org
            orphanRemoval: false
    lifecycleCallbacks: {  }
