BackendBundle\Entity\TblCategoriaClase:
    type: entity
    table: tbl_categoria_clase
    uniqueConstraints:
        keyName:
            columns:
                - keyname
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreCategoria:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: nombre_categoria
        keyname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        descripcion:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        isMultiselect:
            type: boolean
            nullable: true
            column: is_multiselect
        isOrdered:
            type: boolean
            nullable: true
            column: is_ordered
    lifecycleCallbacks: {  }
