BackendBundle\Entity\TblInstituciones:
    type: entity
    table: tbl_instituciones
    id:
        idInstitucion:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_institucion
            generator:
                strategy: SEQUENCE
    fields:
        codInstitucion:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: cod_institucion
        nombreInstitucion:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: nombre_institucion
        acronimo:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        activo:
            type: boolean
            nullable: true
            options:
                default: true
    lifecycleCallbacks: {  }
