BackendBundle\Entity\TblOrganizacionesTipo:
    type: entity
    table: tbl_organizaciones_tipo
    id:
        idOrgType:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_org_type
            generator:
                strategy: SEQUENCE
    fields:
        orgTypeNombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: org_type_nombre
        orgTypeCode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: org_type_code
    lifecycleCallbacks: {  }
