BackendBundle\Entity\TblProgramasConfig:
    type: entity
    table: tbl_programas_config
    indexes:
        fki_config_theme:
            columns:
                - id_herencia
    id:
        idProgramaConfig:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_programa_config
            generator:
                strategy: SEQUENCE
    fields:
        permiteNiveles:
            type: boolean
            nullable: true
            options:
                default: true
            column: permite_niveles
        nombreProgramaConfig:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: nombre_programa_config
    manyToOne:
        idHerencia:
            targetEntity: TblProgramas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_herencia:
                    referencedColumnName: id_programa
            orphanRemoval: false
    lifecycleCallbacks: {  }
