BackendBundle\Entity\TblProyectoPrograma:
    type: entity
    table: tbl_proyecto_programa
    indexes:
        fki_program_proy:
            columns:
                - id_programa
        IDX_F12D41A7DF4AB2EC:
            columns:
                - id_programa_config
    id:
        idProyectoPrograma:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_proyecto_programa
            generator:
                strategy: SEQUENCE
    fields:
        idProyecto:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_proyecto
    manyToOne:
        idProgramaConfig:
            targetEntity: TblProgramasConfig
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_programa_config:
                    referencedColumnName: id_programa_config
            orphanRemoval: false
        idPrograma:
            targetEntity: TblProgramas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_programa:
                    referencedColumnName: id_programa
            orphanRemoval: false
    lifecycleCallbacks: {  }
