BackendBundle\Entity\TblProyectoLocalidad:
    type: entity
    table: tbl_proyecto_localidad
    indexes:
        idx_proyecto_localidad:
            columns:
                - id_proyecto
        idx_localidades:
            columns:
                - id_localidad
    id:
        idProyectoLocalidad:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_proyecto_localidad
            generator:
                strategy: SEQUENCE
    fields:
        idProyecto:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_proyecto
        porcentajePart:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: porcentaje_part
    manyToOne:
        idLocalidad:
            targetEntity: TblLocalidades
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_localidad:
                    referencedColumnName: id_localidad
            orphanRemoval: false
    lifecycleCallbacks: {  }
